# Generated by Django 6.0.3 on 2026-04-02 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greydy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Грейд',
                'verbose_name_plural': 'Грейды',
            },
        ),
        migrations.CreateModel(
            name='Mesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='Modeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Oblasti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=150, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Области',
            },
        ),
        migrations.CreateModel(
            name='Otvetstvennye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('aktiven', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Ответственный',
                'verbose_name_plural': 'Ответственные',
            },
        ),
        migrations.CreateModel(
            name='Smeny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
            },
        ),
        migrations.CreateModel(
            name='Stancii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Станция',
                'verbose_name_plural': 'Станции',
            },
        ),
        migrations.CreateModel(
            name='Tipy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='Avtomobili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN')),
                ('data_sozdaniya', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='defects_app.modeli', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='StatusAvto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='Статус')),
                ('data_statusa', models.DateTimeField(auto_now_add=True, verbose_name='Дата статуса')),
                ('kto_izmenil', models.CharField(blank=True, max_length=150, null=True, verbose_name='Кто изменил')),
                ('avto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects_app.avtomobili', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Статус авто',
                'verbose_name_plural': 'Статусы авто',
            },
        ),
        migrations.CreateModel(
            name='Defekty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('kommentarij', models.TextField(blank=True, null=True, verbose_name='Комментаррий')),
                ('kto_sozdal', models.CharField(blank=True, max_length=150, null=True, verbose_name='Кто создал')),
                ('ustraneno', models.BooleanField(default=False, verbose_name='Устранено')),
                ('kto_ustranil', models.CharField(blank=True, max_length=150, null=True, verbose_name='Кто устранил')),
                ('data_ustraneniya', models.DateTimeField(blank=True, null=True, verbose_name='Дата устранения')),
                ('avto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects_app.avtomobili', verbose_name='Автомобиль')),
                ('greyd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='defects_app.greydy', verbose_name='Грейд')),
                ('mesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='defects_app.mesta', verbose_name='Место')),
                ('oblast', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='defects_app.oblasti', verbose_name='Область')),
                ('otvetstvennyj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='defects_app.otvetstvennye', verbose_name='Ответственный')),
                ('smena', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='defects_app.smeny', verbose_name='Смена')),
                ('stanciya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='defects_app.stancii', verbose_name='Станция')),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='defects_app.tipy', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Дефект',
                'verbose_name_plural': 'Дефекты',
            },
        ),
    ]
