# Generated by Django 6.0.3 on 2026-04-03 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defekty',
            name='otvetstvennyj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='defects_app.otvetstvennye', verbose_name='Ответственный'),
        ),
    ]
