# Generated by Django 6.0.3 on 2026-04-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects_app', '0002_alter_defekty_otvetstvennyj'),
    ]

    operations = [
        migrations.AddField(
            model_name='defekty',
            name='data_razresheniya',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата разрешения'),
        ),
        migrations.AddField(
            model_name='defekty',
            name='kto_razreshil',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Кто разрешил'),
        ),
        migrations.AddField(
            model_name='defekty',
            name='proveren',
            field=models.BooleanField(default=False, verbose_name='Проверен'),
        ),
    ]
