# Generated by Django 6.0.3 on 2026-04-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects_app', '0003_defekty_data_razresheniya_defekty_kto_razreshil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avtomobili',
            name='data_prohoda_bestenevaya',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата прохода Бестеневой'),
        ),
        migrations.AddField(
            model_name='avtomobili',
            name='proshla_bestenevaya',
            field=models.BooleanField(default=False, verbose_name='Прошла Бестеневую'),
        ),
    ]
