# Generated by Django 6.0.3 on 2026-04-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects_app', '0005_avtomobili_telematika'),
    ]

    operations = [
        migrations.AddField(
            model_name='avtomobili',
            name='glonass',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Глонасс'),
        ),
    ]
