# Generated by Django 6.0.3 on 2026-04-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects_app', '0006_avtomobili_glonass'),
    ]

    operations = [
        migrations.AddField(
            model_name='avtomobili',
            name='batareya',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Батарея'),
        ),
    ]
