# Generated by Django 6.0.3 on 2026-04-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects_app', '0007_avtomobili_batareya'),
    ]

    operations = [
        migrations.AddField(
            model_name='avtomobili',
            name='perednij_dvigatel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Передний двигатель'),
        ),
        migrations.AddField(
            model_name='avtomobili',
            name='vid_dvigatelya',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Вид двигателя'),
        ),
        migrations.AddField(
            model_name='avtomobili',
            name='zadnij_dvigatel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Задний двигатель'),
        ),
    ]
