# Generated by Django 6.0.3 on 2026-04-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defects_app', '0008_avtomobili_perednij_dvigatel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avtomobili',
            name='vid_dvigatelya',
        ),
    ]
