# Generated by Django 6.0.3 on 2026-04-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects_app', '0009_remove_avtomobili_vid_dvigatelya'),
    ]

    operations = [
        migrations.AddField(
            model_name='avtomobili',
            name='glonass_iccid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ICCID Глонасс'),
        ),
        migrations.AddField(
            model_name='avtomobili',
            name='glonass_imei',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IMEI Глонасс'),
        ),
        migrations.AddField(
            model_name='avtomobili',
            name='glonass_sn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Серийный номер'),
        ),
    ]
