# Generated by Django 6.0.3 on 2026-04-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects_app', '0010_avtomobili_glonass_iccid_avtomobili_glonass_imei_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avtomobili',
            name='kto_sozdal',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Кто создал машину'),
        ),
    ]
