# Generated by Django 6.0.3 on 2026-04-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects_app', '0011_avtomobili_kto_sozdal'),
    ]

    operations = [
        migrations.AddField(
            model_name='avtomobili',
            name='data_privyazki_telematiki',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Дата привязки телематики'),
        ),
        migrations.AddField(
            model_name='avtomobili',
            name='privyazal_telematiku',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Привязал телематику'),
        ),
    ]
