# Generated by Django 6.0.3 on 2026-04-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects_app', '0012_avtomobili_data_privyazki_telematiki_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avtomobili',
            name='data_privyazki_telematiki',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата привязки телематики'),
        ),
    ]
