# Generated by Django 6.0.3 on 2026-04-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects_app', '0013_alter_avtomobili_data_privyazki_telematiki'),
    ]

    operations = [
        migrations.AddField(
            model_name='avtomobili',
            name='glonass_kogda',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата привязки глонасса'),
        ),
        migrations.AddField(
            model_name='avtomobili',
            name='glonass_kto',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Привязал глонасс'),
        ),
    ]
