# Generated by Django 6.0.3 on 2026-04-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects_app', '0014_avtomobili_glonass_kogda_avtomobili_glonass_kto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avtomobili',
            name='glonass_kogda',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата привязки батареи'),
        ),
        migrations.AlterField(
            model_name='avtomobili',
            name='glonass_kto',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Привязал батарею'),
        ),
    ]
