# Generated by Django 6.0.3 on 2026-04-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects_app', '0015_alter_avtomobili_glonass_kogda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avtomobili',
            name='batareya_kogda',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата привязки батареи'),
        ),
        migrations.AddField(
            model_name='avtomobili',
            name='batareya_kto',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Привязал батарею'),
        ),
        migrations.AlterField(
            model_name='avtomobili',
            name='glonass_kogda',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата привязки глонасса'),
        ),
        migrations.AlterField(
            model_name='avtomobili',
            name='glonass_kto',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Привязал глонасс'),
        ),
    ]
