# Generated by Django 6.0.3 on 2026-04-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects_app', '0016_avtomobili_batareya_kogda_avtomobili_batareya_kto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avtomobili',
            name='perednij_dvigatel_kogda',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата привязки переднего двигателя'),
        ),
        migrations.AddField(
            model_name='avtomobili',
            name='perednij_dvigatel_kto',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Привязал передний двигатель'),
        ),
        migrations.AddField(
            model_name='avtomobili',
            name='zadnij_dvigatel_kogda',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата привязки заднего двигателя'),
        ),
        migrations.AddField(
            model_name='avtomobili',
            name='zadnij_dvigatel_kto',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Привязал задний двигатель'),
        ),
    ]
