# Generated by Django 6.0.3 on 2026-04-13 14:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects_app', '0017_avtomobili_perednij_dvigatel_kogda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IstoriyaIzmeneniyAvto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pole', models.CharField(max_length=100, verbose_name='Поле')),
                ('staroe_znachenie', models.TextField(blank=True, null=True, verbose_name='Старое значение')),
                ('novoe_znachenie', models.TextField(blank=True, null=True, verbose_name='Новое значение')),
                ('kto_izmenil', models.CharField(max_length=150, verbose_name='Кто изменил')),
                ('data_izmeneniya', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения')),
                ('avto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istoriya_izmeneniy_avto', to='defects_app.avtomobili', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'История изменения автомобиля',
                'verbose_name_plural': 'История изменений автомобилей',
                'ordering': ['-data_izmeneniya'],
            },
        ),
        migrations.CreateModel(
            name='IstoriyaIzmeneniyDefektov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pole', models.CharField(max_length=100, verbose_name='Поле')),
                ('staroe_znachenie', models.TextField(blank=True, null=True, verbose_name='Старое значение')),
                ('novoe_znachenie', models.TextField(blank=True, null=True, verbose_name='Новое значение')),
                ('kto_izmenil', models.CharField(max_length=150, verbose_name='Кто изменил')),
                ('data_izmeneniya', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения')),
                ('defekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istoriya_izmeneniy_defektov', to='defects_app.defekty', verbose_name='Дефект')),
            ],
            options={
                'verbose_name': 'История изменения дефекта',
                'verbose_name_plural': 'История изменений дефектов',
                'ordering': ['-data_izmeneniya'],
            },
        ),
    ]
