# Generated by Django 6.0.3 on 2026-04-27 09:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects_app', '0018_istoriyaizmeneniyavto_istoriyaizmeneniydefektov'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnpDefectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий причины отправки на СНП')),
                ('kto_sozdal', models.CharField(max_length=150, verbose_name='Кто создал')),
                ('data_sozdaniya', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('kto_izmenil', models.CharField(blank=True, max_length=150, null=True, verbose_name='Кто изменил')),
                ('data_izmeneniya', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('avto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snp_comments', to='defects_app.avtomobili', verbose_name='Автомобиль')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snp_comments', to='defects_app.defekty', verbose_name='Дефект')),
            ],
            options={
                'verbose_name': 'Комментарий СНП по дефекту',
                'verbose_name_plural': 'Комментарии СНП по дефектам',
                'ordering': ['-data_sozdaniya'],
            },
        ),
        migrations.CreateModel(
            name='SnpDefectOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, verbose_name='Номер заказа')),
                ('kto_sozdal', models.CharField(max_length=150, verbose_name='Кто внёс')),
                ('data_sozdaniya', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата внесения')),
                ('kto_izmenil', models.CharField(blank=True, max_length=150, null=True, verbose_name='Кто изменил')),
                ('data_izmeneniya', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('avto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snp_orders', to='defects_app.avtomobili', verbose_name='Автомобиль')),
                ('defect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snp_order', to='defects_app.defekty', verbose_name='Дефект')),
            ],
            options={
                'verbose_name': 'Заказ СНП по дефекту',
                'verbose_name_plural': 'Заказы СНП по дефектам',
            },
        ),
    ]
