# Generated by Django 6.0.3 on 2026-05-03 08:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects_app', '0019_snpdefectcomment_snpdefectorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanovyeVin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer_partii', models.CharField(max_length=50, verbose_name='№ партии')),
                ('nomer_lota', models.CharField(max_length=100, verbose_name='№ лота')),
                ('model', models.CharField(max_length=150, verbose_name='Модель')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN рус')),
                ('cvet_kuzova', models.CharField(max_length=100, verbose_name='Цвет кузова')),
                ('cvet_salona', models.CharField(max_length=100, verbose_name='Цвет салона')),
                ('komplektaciya', models.CharField(max_length=150, verbose_name='Комплектация')),
                ('otts', models.CharField(max_length=100, verbose_name='ОТТС')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя файла')),
                ('kto_zagruzil', models.CharField(blank=True, max_length=150, null=True, verbose_name='Кто загрузил')),
                ('data_zagruzki', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Плановый VIN',
                'verbose_name_plural': 'Плановые VIN',
                'ordering': ['id'],
            },
        ),
    ]
