# Generated by Django 6.0.3

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defects_app", "0032_avtomobili_created_on_station_1"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="defectphoto",
            options={
                "ordering": ["uploaded_at"],
                "verbose_name": "Фото дефекта",
                "verbose_name_plural": "Фото дефектов",
            },
        ),
        migrations.AlterField(
            model_name="defectphoto",
            name="image",
            field=models.ImageField(
                upload_to="defects_photos/%Y/%m/%d/",
                verbose_name="Фото дефекта",
            ),
        ),
        migrations.AlterField(
            model_name="defectphoto",
            name="uploaded_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Дата загрузки",
            ),
        ),
    ]