# Generated by Django 6.0.3 on 2026-05-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects_app', '0033_alter_defectphoto_options_alter_defectphoto_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер контейнера')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContainerReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_number', models.PositiveIntegerField(verbose_name='Номер акта за день')),
                ('receipt_date', models.DateField(verbose_name='Дата поступления')),
                ('vehicle_number', models.CharField(max_length=20, verbose_name='Номер машины')),
                ('components_name', models.CharField(blank=True, max_length=255, verbose_name='Наименование комплектующих изделий')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Номер партии')),
                ('package_number', models.CharField(blank=True, max_length=100, verbose_name='Номер упаковки')),
                ('package_marking', models.CharField(blank=True, max_length=255, verbose_name='Маркировка упаковочной тары')),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('container', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='receipts',
                    to='defects_app.container'
                )),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContainerReceiptPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='container_receipts/%Y/%m/%d/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_by', models.CharField(blank=True, max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('receipt', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='photos',
                    to='defects_app.containerreceipt'
                )),
            ],
        ),
        migrations.CreateModel(
            name='ContainerSeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seal_number', models.CharField(max_length=100, verbose_name='Номер пломбы')),
                ('receipt', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='seals',
                    to='defects_app.containerreceipt'
                )),
            ],
        ),
    ]