# Generated by Django 6.0.3

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defects_app", "0034_container_containerreceipt_containerreceiptphoto_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainerCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accepted_by",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "avto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="container_receipts",
                        to="defects_app.avtomobili",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="defects_app.containerreceipt",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]