# Generated by Django 6.0.3 on 2026-06-02 09:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defects_app", "0036_containercarphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="avtomobili",
            name="station1_sequence_number",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                unique=True,
                verbose_name="Sequence номер станции 1",
            ),
        ),
        migrations.CreateModel(
            name="StationOnePrintBufferEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Когда добавлена в буфер",
                    ),
                ),
                (
                    "printed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Когда отправлена в 6-листник",
                    ),
                ),
                (
                    "car",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station1_print_buffer_entry",
                        to="defects_app.avtomobili",
                        verbose_name="Автомобиль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись буфера станции 1",
                "verbose_name_plural": "Буфер станции 1",
                "ordering": ["added_at", "id"],
            },
        ),
    ]