# Generated by Codex on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defects_app", "0037_avtomobili_station1_sequence_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="containerreceipt",
            name="submission_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]