# Generated by Django 6.0.3 on 2026-06-05 09:32

from django.db import migrations, models
from django.db.models import Count, Min


def merge_duplicate_container_car_links(apps, schema_editor):
    ContainerCar = apps.get_model("defects_app", "ContainerCar")
    ContainerCarPhoto = apps.get_model("defects_app", "ContainerCarPhoto")

    duplicates = (
        ContainerCar.objects.values("receipt_id", "avto_id")
        .annotate(link_count=Count("id"), keeper_id=Min("id"))
        .filter(link_count__gt=1)
    )

    for duplicate in duplicates:
        duplicate_ids = list(
            ContainerCar.objects.filter(
                receipt_id=duplicate["receipt_id"],
                avto_id=duplicate["avto_id"],
            )
            .exclude(id=duplicate["keeper_id"])
            .values_list("id", flat=True)
        )

        ContainerCarPhoto.objects.filter(container_car_id__in=duplicate_ids).update(
            container_car_id=duplicate["keeper_id"]
        )
        ContainerCar.objects.filter(id__in=duplicate_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("defects_app", "0038_containerreceipt_submission_token"),
    ]

    operations = [
        migrations.RunPython(
            merge_duplicate_container_car_links,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="containercar",
            constraint=models.UniqueConstraint(
                fields=("receipt", "avto"), name="unique_container_car_per_receipt"
            ),
        ),
    ]