# Generated by Codex on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defects_app", "0039_unique_container_car_per_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="avtomobili",
            name="dvs",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="ДВС"),
        ),
        migrations.AddField(
            model_name="avtomobili",
            name="dvs_kto",
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Привязал ДВС"),
        ),
        migrations.AddField(
            model_name="avtomobili",
            name="dvs_kogda",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата привязки ДВС"),
        ),
    ]