# Generated by Django 6.0.3 on 2026-06-09 18:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defects_app", "0040_avtomobili_dvs"),
    ]

    operations = [
        migrations.CreateModel(
            name="WmsCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_number",
                    models.CharField(max_length=100, verbose_name="Номер кейса"),
                ),
            ],
            options={
                "verbose_name": "WMS кейс",
                "verbose_name_plural": "WMS кейсы",
                "ordering": ["case_number"],
            },
        ),
        migrations.CreateModel(
            name="WmsLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lot_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Номер лота"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="wms/lots/%Y/%m/%d/",
                        verbose_name="Исходный Excel-файл",
                    ),
                ),
                (
                    "uploaded_by",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Кто загрузил"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "WMS лот",
                "verbose_name_plural": "WMS лоты",
                "ordering": ["-uploaded_at"],
                "permissions": [
                    ("wms_view", "Can view WMS"),
                    ("wms_import_lot", "Can import WMS lots"),
                    ("wms_place", "Can place WMS pallets"),
                    ("wms_move", "Can move WMS pallets"),
                    ("wms_admin", "Can administrate WMS"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WmsPalletType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Код"),
                ),
                (
                    "width_units",
                    models.PositiveIntegerField(
                        verbose_name="Ширина, условные единицы"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "WMS тип поддона",
                "verbose_name_plural": "WMS типы поддонов",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="WmsStorageCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_number", models.PositiveIntegerField(verbose_name="Столбец")),
                ("level_number", models.PositiveIntegerField(verbose_name="Этаж")),
                (
                    "capacity_units",
                    models.PositiveIntegerField(
                        default=6, verbose_name="Вместимость, условные единицы"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "WMS ячейка",
                "verbose_name_plural": "WMS ячейки",
                "ordering": [
                    "line__sort_order",
                    "line__code",
                    "column_number",
                    "level_number",
                ],
            },
        ),
        migrations.CreateModel(
            name="WmsStorageLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="Код ряда")),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Название"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "WMS ряд склада",
                "verbose_name_plural": "WMS ряды склада",
                "ordering": ["warehouse__site__code", "warehouse__code", "sort_order", "code"],
            },
        ),

        migrations.CreateModel(
            name="WmsSite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="Код площадки")),
                ("name", models.CharField(max_length=150, verbose_name="Название площадки")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
            ],
            options={
                "verbose_name": "WMS площадка",
                "verbose_name_plural": "WMS площадки",
                "ordering": ["code"],
            },
        ),

        migrations.CreateModel(
            name="WmsWarehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название склада"),
                ),
                (
                    "code",
                    models.CharField(max_length=50, verbose_name="Код склада"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouses",
                        to="defects_app.wmssite",
                        verbose_name="Площадка",
                    ),
                ),
            ],
            options={
                "verbose_name": "WMS склад",
                "verbose_name_plural": "WMS склады",
                "ordering": ["site__code", "code"],
            },
        ),
        migrations.CreateModel(
            name="WmsBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "box_number",
                    models.CharField(max_length=100, verbose_name="Номер коробки"),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boxes",
                        to="defects_app.wmscase",
                        verbose_name="Кейс",
                    ),
                ),
            ],
            options={
                "verbose_name": "WMS коробка",
                "verbose_name_plural": "WMS коробки",
                "ordering": ["box_number"],
            },
        ),
        migrations.CreateModel(
            name="WmsContainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "container_number",
                    models.CharField(max_length=100, verbose_name="Номер контейнера"),
                ),
                (
                    "seal_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Номер пломбы"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "existing_container",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wms_containers",
                        to="defects_app.container",
                        verbose_name="Связанный контейнер приемки",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="containers",
                        to="defects_app.wmslot",
                        verbose_name="Лот",
                    ),
                ),
            ],
            options={
                "verbose_name": "WMS контейнер",
                "verbose_name_plural": "WMS контейнеры",
                "ordering": ["container_number"],
            },
        ),
        migrations.AddField(
            model_name="wmscase",
            name="container",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases",
                to="defects_app.wmscontainer",
                verbose_name="Контейнер",
            ),
        ),

        migrations.CreateModel(
            name="WmsStorageUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unit_type", models.CharField(
                    choices=[("CONTAINER", "Контейнер"), ("CASE", "Кейс"), ("BOX", "Коробка")],
                    max_length=30,
                    verbose_name="Тип складской единицы",
                )),
                ("label", models.CharField(blank=True, max_length=150, verbose_name="Метка / номер складской единицы")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата создания")),
                ("created_by", models.CharField(blank=True, max_length=150, verbose_name="Кто создал")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                ("container", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="storage_units",
                    to="defects_app.wmscontainer",
                    verbose_name="Контейнер",
                )),
                ("case", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="storage_units",
                    to="defects_app.wmscase",
                    verbose_name="Кейс",
                )),
                ("box", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="storage_units",
                    to="defects_app.wmsbox",
                    verbose_name="Коробка",
                )),
            ],
            options={
                "verbose_name": "WMS складская единица",
                "verbose_name_plural": "WMS складские единицы",
                "ordering": ["unit_type", "label", "id"],
            },
        ),

        migrations.CreateModel(
            name="WmsPallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pallet_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Номер поддона"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата создания"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Кто создал"
                    ),
                ),
                (
                    "storage_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pallets",
                        to="defects_app.wmsstorageunit",
                        verbose_name="Складская единица",
                    ),
                ),
                (
                    "pallet_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pallets",
                        to="defects_app.wmspallettype",
                        verbose_name="Тип поддона",
                    ),
                ),
            ],
            options={
                "verbose_name": "WMS поддон",
                "verbose_name_plural": "WMS поддоны",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WmsPalletPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_from",
                    models.PositiveIntegerField(verbose_name="Позиция с"),
                ),
                ("position_to", models.PositiveIntegerField(verbose_name="Позиция по")),
                (
                    "placed_by",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Кто разместил"
                    ),
                ),
                (
                    "placed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Когда разместил",
                    ),
                ),
                (
                    "removed_by",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Кто снял"
                    ),
                ),
                (
                    "removed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Когда снял"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "pallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="defects_app.wmspallet",
                        verbose_name="Поддон",
                    ),
                ),
                (
                    "cell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements",
                        to="defects_app.wmsstoragecell",
                        verbose_name="Ячейка",
                    ),
                ),
            ],
            options={
                "verbose_name": "WMS размещение поддона",
                "verbose_name_plural": "WMS размещения поддонов",
                "ordering": [
                    "-is_active",
                    "cell__line__code",
                    "cell__column_number",
                    "cell__level_number",
                    "position_from",
                ],
            },
        ),
        migrations.AddField(
            model_name="wmsstoragecell",
            name="line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cells",
                to="defects_app.wmsstorageline",
                verbose_name="Ряд",
            ),
        ),
        migrations.AddField(
            model_name="wmsstorageline",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="defects_app.wmswarehouse",
                verbose_name="Склад",
            ),
        ),
        migrations.CreateModel(
            name="WmsBoxItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_number",
                    models.CharField(max_length=150, verbose_name="SAP Part Number"),
                ),
                (
                    "chinese_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Китайское наименование",
                    ),
                ),
                (
                    "chinese_description",
                    models.TextField(blank=True, verbose_name="Китайское описание"),
                ),
                (
                    "english_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Английское наименование",
                    ),
                ),
                (
                    "english_description",
                    models.TextField(blank=True, verbose_name="Английское описание"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Количество",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Ед. изм."
                    ),
                ),
                (
                    "gross_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Вес брутто",
                    ),
                ),
                (
                    "net_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Вес нетто",
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Объем",
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Исходная строка Excel"
                    ),
                ),
                (
                    "box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="defects_app.wmsbox",
                        verbose_name="Коробка",
                    ),
                ),
            ],
            options={
                "verbose_name": "WMS позиция коробки",
                "verbose_name_plural": "WMS позиции коробок",
                "ordering": ["part_number", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("box", "part_number"),
                        name="unique_wms_item_part_per_box",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="wmsbox",
            constraint=models.UniqueConstraint(
                fields=("case", "box_number"), name="unique_wms_box_per_case"
            ),
        ),
        migrations.AddConstraint(
            model_name="wmscase",
            constraint=models.UniqueConstraint(
                fields=("container", "case_number"),
                name="unique_wms_case_per_container",
            ),
        ),
        migrations.AddConstraint(
            model_name="wmscontainer",
            constraint=models.UniqueConstraint(
                fields=("lot", "container_number"), name="unique_wms_container_per_lot"
            ),
        ),
        migrations.AddConstraint(
            model_name="wmspalletplacement",
            constraint=models.CheckConstraint(
                condition=models.Q(("position_from__gte", 1)),
                name="wms_placement_position_from_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="wmspalletplacement",
            constraint=models.CheckConstraint(
                condition=models.Q(("position_to__gte", 1)),
                name="wms_placement_position_to_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="wmspalletplacement",
            constraint=models.CheckConstraint(
                condition=models.Q(("position_to__gte", models.F("position_from"))),
                name="wms_placement_position_to_gte_from",
            ),
        ),
        migrations.AddConstraint(
            model_name="wmspalletplacement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("pallet",),
                name="unique_active_wms_placement_per_pallet",
            ),
        ),
        migrations.AddConstraint(
            model_name="wmsstoragecell",
            constraint=models.UniqueConstraint(
                fields=("line", "column_number", "level_number"),
                name="unique_wms_cell_per_line_column_level",
            ),
        ),
        migrations.AddConstraint(
            model_name="wmsstorageline",
            constraint=models.UniqueConstraint(
                fields=("warehouse", "code"), name="unique_wms_line_per_warehouse"
            ),
        ),
        migrations.AddConstraint(
            model_name="wmswarehouse",
            constraint=models.UniqueConstraint(
                fields=("site", "code"),
                name="unique_wms_warehouse_per_site",
            ),
        ),
        migrations.AddConstraint(
            model_name="wmsstorageunit",
            constraint=models.UniqueConstraint(
                fields=("unit_type", "container"),
                condition=models.Q(("container__isnull", False)),
                name="unique_wms_storage_unit_container",
            ),
        ),
        migrations.AddConstraint(
            model_name="wmsstorageunit",
            constraint=models.UniqueConstraint(
                fields=("unit_type", "case"),
                condition=models.Q(("case__isnull", False)),
                name="unique_wms_storage_unit_case",
            ),
        ),
        migrations.AddConstraint(
            model_name="wmsstorageunit",
            constraint=models.UniqueConstraint(
                fields=("unit_type", "box"),
                condition=models.Q(("box__isnull", False)),
                name="unique_wms_storage_unit_box",
            ),
        ),
        migrations.AddConstraint(
            model_name="wmsstorageunit",
            constraint=models.CheckConstraint(
                condition=(
                    (
                        models.Q(("container__isnull", False))
                        & models.Q(("case__isnull", True))
                        & models.Q(("box__isnull", True))
                    )
                    |
                    (
                        models.Q(("container__isnull", True))
                        & models.Q(("case__isnull", False))
                        & models.Q(("box__isnull", True))
                    )
                    |
                    (
                        models.Q(("container__isnull", True))
                        & models.Q(("case__isnull", True))
                        & models.Q(("box__isnull", False))
                    )
                ),
                name="wms_storage_unit_exactly_one_object",
            ),
        ),
    ]