# Generated by Django 6.0.3 on 2026-06-13 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects_app', '0044_wms_issue_active_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmslot',
            name='site',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='lots',
                to='defects_app.wmssite',
                verbose_name='Площадка',
            ),
        ),
        migrations.AlterField(
            model_name='wmslot',
            name='lot_number',
            field=models.CharField(
                max_length=100,
                verbose_name='Номер лота',
            ),
        ),
        migrations.AddConstraint(
            model_name='wmslot',
            constraint=models.UniqueConstraint(
                fields=('site', 'lot_number'),
                name='unique_wms_lot_per_site',
            ),
        ),
    ]