from django.urls import path
from .views import (
    home,
    create_defect,
    check_vin,
    edit_defect,
    delete_defect,
    okline_view,
    complete_bestenevaya,
    telematika_view,
    glonass_view,
    batareya_view,
    perednij_dvigatel_view,
    zadnij_dvigatel_view,
    quality_view,
    vh1_view,
    dovodka_view,
    create_car_view,
    manager_dashboard_view,
    manager_login_view,
    print_created_car_view,
    print_created_car_info_view,
    print_created_car_info_batch_view,
    print_sgp_report_view,
    manager_open_station_view,
    manager_open_vh1_station_view,
    open_station_for_department_view,
    open_vh1_station_for_department_view,
    snp_orders_view,
    upload_plan_vin_view,
    telematika_glonass_view,
    live_cars_view,
    logistics_live_cars_view,
    exports_view,
    export_defects_view,
    export_created_cars_view,
    production_plans_view,
    qrqc_oee_api_view,
    reports_view,
    oee_report_view,
    oee_print_view,
    qrqc_dashboard_view,   
    bestenevaya_timer_api_view,
    qrqc_dphu_api_view,
    dphu_report_view,
    qrqc_top_defects_api_view,
    top_defects_report_view,
    top_defects_api_view,  
    qrqc_print_view,
    agregaty_view,
    qrqc_snp_api_view,
    export_qrqc_production_view,
    vin_prefixes_api_view,
    vin_model_api_view,
    upload_old_snp_cars_view,
    export_snp_cars_view,
    export_full_cars_view,
    qrqc_direct_pass_api_view,
    defect_photo_detail_view,
    defect_types_dashboard_view,
    defect_types_dashboard_api_view,
    export_defect_types_dashboard_view,
    department_hub_view,
    department_section_view,
)

urlpatterns = [
    path("", home, name="home"),
    path("create-defect/<int:car_id>/", create_defect, name="create_defect"),
    path("edit-defect/<int:defect_id>/", edit_defect, name="edit_defect"),
    path("delete-defect/<int:defect_id>/", delete_defect, name="delete_defect"),
    path("okline/", okline_view, name="okline"),
    path("complete-bestenevaya/<int:car_id>/", complete_bestenevaya, name="complete_bestenevaya"),
    path("check-vin/", check_vin, name="check_vin"),
    path("telematika/", telematika_view, name="telematika"),
    path("glonass/", glonass_view, name="glonass"),
    path("batareya/", batareya_view, name="batareya"),
    path("perednij-dvigatel/", perednij_dvigatel_view, name="perednij_dvigatel"),
    path("zadnij-dvigatel/", zadnij_dvigatel_view, name="zadnij_dvigatel"),
    path("quality/", quality_view, name="quality"),
    path("vh1/", vh1_view, name="vh1"),
    path("dovodka/", dovodka_view, name="dovodka"),
    path("create-car/", create_car_view, name="create_car"),
    path("print-created-car/<int:car_id>/", print_created_car_view, name="print_created_car"),
    path("print-created-car-info/<int:car_id>/", print_created_car_info_view, name="print_created_car_info"),
    path("print-created-car-info-batch/", print_created_car_info_batch_view, name="print_created_car_info_batch"),
    path("print-sgp-report/<int:car_id>/", print_sgp_report_view, name="print_sgp_report"),
    path("manager/", manager_dashboard_view, name="manager_dashboard"),
    path("manager-login/", manager_login_view, name="manager_login"),
    path("manager/open-station/<int:station_id>/", manager_open_station_view, name="manager_open_station"),
    path("manager/open-station-vh1/", manager_open_vh1_station_view, name="manager_open_vh1_station"),
    path("open-station/<int:station_id>/", open_station_for_department_view, name="open_station_for_department"),
    path("open-station-vh1/", open_vh1_station_for_department_view, name="open_vh1_station_for_department"),
    path("snp-orders/", snp_orders_view, name="snp_orders"),
    path("upload-plan-vin/", upload_plan_vin_view, name="upload_plan_vin"),
    path("telematika-glonass/", telematika_glonass_view, name="telematika_glonass"),
    path("live-cars/", live_cars_view, name="live_cars"),
    path("logistics-live-cars/", logistics_live_cars_view, name="logistics_live_cars"),
    path("exports/", exports_view, name="exports"),    
    path("exports/defects/", export_defects_view, name="export_defects"),
    path("exports/created-cars/", export_created_cars_view, name="export_created_cars"),
    path("plans/", production_plans_view, name="production_plans"),    
    path("reports/", reports_view, name="reports"),
    path("reports/oee/api/", qrqc_oee_api_view, name="oee_api"),
    path("reports/oee/", oee_report_view, name="oee_report"),
    path("reports/oee/print/", oee_print_view, name="oee_print"),
    path("reports/qrqc/", qrqc_dashboard_view, name="qrqc_dashboard"),
    path("bestenevaya/timer-api/", bestenevaya_timer_api_view, name="bestenevaya_timer_api"),
    path("reports/qrqc/dphu-api/", qrqc_dphu_api_view, name="qrqc_dphu_api"),
    path("reports/dphu/", dphu_report_view, name="dphu_report"),    
    path("reports/qrqc/top-defects-api/", qrqc_top_defects_api_view, name="qrqc_top_defects_api"),
    path("reports/top-defects/", top_defects_report_view, name="top_defects_report"),
    path("reports/top-defects/api/", top_defects_api_view, name="top_defects_api"),
    path("reports/qrqc/print/", qrqc_print_view, name="qrqc_print"),
    path("agregaty/", agregaty_view, name="agregaty"),
    path("reports/qrqc/snp-api/", qrqc_snp_api_view, name="qrqc_snp_api"),
    path("reports/qrqc/export-production/", export_qrqc_production_view, name="export_qrqc_production"),
    path("vin-prefixes-api/", vin_prefixes_api_view, name="vin_prefixes_api"),
    path("vin-model-api/", vin_model_api_view, name="vin_model_api"),
    path("upload-old-snp-cars/", upload_old_snp_cars_view, name="upload_old_snp_cars"),
    path("exports/snp-cars/", export_snp_cars_view, name="export_snp_cars"),
    path("exports/full-cars/", export_full_cars_view, name="export_full_cars"),
    path("reports/qrqc/direct-pass-api/", qrqc_direct_pass_api_view, name="qrqc_direct_pass_api"),
    path("defect-photo-detail/<int:defect_id>/", defect_photo_detail_view, name="defect_photo_detail"),
    path("reports/defect-types/", defect_types_dashboard_view, name="defect_types_dashboard"),
    path("reports/defect-types/api/", defect_types_dashboard_api_view, name="defect_types_dashboard_api"),
    path("reports/defect-types/export/", export_defect_types_dashboard_view, name="export_defect_types_dashboard"),
    path("department-hub/", department_hub_view, name="department_hub"),
    path("department/<str:section>/", department_section_view, name="department_section"),
]